<a href="https://colab.research.google.com/github/dusarp/dance-bits-experiments/blob/main/bone_vectors_pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pickle
import numpy as np

In [2]:
#mount Google Drive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
from google.colab import files
uploaded = files.upload()

Saving gBR_sFM_c01_d04_mBR3_ch04.p to gBR_sFM_c01_d04_mBR3_ch04.p


In [4]:
# Open the pickle file in binary read mode
with open('/content/gBR_sFM_c01_d04_mBR3_ch04.p', 'rb') as file:
    # Load the contents of the file
    data = pickle.load(file)

# Now you can use the 'data' variable
print(data)

{'bone_vectors': array([[-0.22098406,  0.4485154 ,  0.3731835 , ...,  0.49884802,
         0.01606774,  0.49974176],
       [-0.2227173 ,  0.44765723,  0.3728047 , ...,  0.497993  ,
         0.01648623,  0.49972814],
       [-0.2716056 ,  0.41979805,  0.31863856, ...,  0.49300647,
         0.00905285,  0.49991804],
       ...,
       [-0.09464655, -0.4909603 , -0.01523619, ...,  0.4428401 ,
         0.29833308, -0.4012448 ],
       [-0.09656103, -0.49058738, -0.0148069 , ...,  0.4428565 ,
         0.30885425, -0.39320356],
       [-0.09524848, -0.4908439 , -0.0147612 , ...,  0.4428701 ,
         0.31336743, -0.38961628]], dtype=float32), 'keypoints': array([[ 0.48376003,  0.43008092, -0.2131675 , ...,  0.790187  ,
         0.06459393,  0.9669076 ],
       [ 0.48375636,  0.42997152, -0.21299468, ...,  0.79160655,
         0.06460377,  0.9673822 ],
       [ 0.48340797,  0.43144178, -0.22610661, ...,  0.791478  ,
         0.08008426,  0.9669033 ],
       ...,
       [ 0.55910534,  0.59513

In [5]:
# Get the type of the object
print(f"Type of loaded object: {type(data)}")

# If it's a list or tuple, get its length
if isinstance(data, (list, tuple)):
    print(f"Number of items: {len(data)}")

# If it's a numpy array, get its shape and dtype
if hasattr(data, 'shape'):
    print(f"Shape: {data.shape}")
    print(f"Data type: {data.dtype}")

# If it's a dictionary, get the number of keys
if isinstance(data, dict):
    print(f"Number of keys: {len(data)}")
    print(f"Keys: {list(data.keys())}")

# Get the total size in memory
import sys
print(f"Size in memory: {sys.getsizeof(data)} bytes")

Type of loaded object: <class 'dict'>
Number of keys: 4
Keys: ['bone_vectors', 'keypoints', 'mel_spectrogram', 'labels']
Size in memory: 232 bytes


In [6]:
data['keypoints']

array([[ 0.48376003,  0.43008092, -0.2131675 , ...,  0.790187  ,
         0.06459393,  0.9669076 ],
       [ 0.48375636,  0.42997152, -0.21299468, ...,  0.79160655,
         0.06460377,  0.9673822 ],
       [ 0.48340797,  0.43144178, -0.22610661, ...,  0.791478  ,
         0.08008426,  0.9669033 ],
       ...,
       [ 0.55910534,  0.59513026, -0.03559213, ...,  0.80694795,
        -0.04327298,  0.98890734],
       [ 0.55920017,  0.59512943, -0.03486083, ...,  0.8069456 ,
        -0.04292793,  0.9890027 ],
       [ 0.55926937,  0.5951558 , -0.03497342, ...,  0.8069437 ,
        -0.04066251,  0.9890649 ]], dtype=float32)

In [7]:
data['keypoints'].shape

(2093, 132)

In [22]:
data['keypoints'][0]

array([ 0.48376003,  0.43008092, -0.2131675 ,  0.9999765 ,  0.486718  ,
        0.42045632, -0.2041832 ,  0.9999275 ,  0.48838928,  0.42031252,
       -0.20418663,  0.9999163 ,  0.49012962,  0.42017454, -0.20420077,
        0.99990153,  0.4802278 ,  0.42089948, -0.20467919,  0.9999331 ,
        0.47820938,  0.4210852 , -0.20471796,  0.99993384,  0.47621572,
        0.42135942, -0.20474757,  0.9999399 ,  0.49267128,  0.4224859 ,
       -0.13683155,  0.999879  ,  0.47414997,  0.42444193, -0.13917294,
        0.99992716,  0.48733208,  0.43837896, -0.18639821,  0.9999783 ,
        0.48006248,  0.43940634, -0.18723902,  0.99998474,  0.50866354,
        0.46942478, -0.07945897,  0.99997294,  0.45843   ,  0.46794027,
       -0.08672278,  0.9998696 ,  0.52181065,  0.5247851 , -0.05018394,
        0.9942676 ,  0.4413354 ,  0.52694553, -0.10012879,  0.9920277 ,
        0.523564  ,  0.5793175 , -0.10785865,  0.98356426,  0.4641665 ,
        0.55588645, -0.18789595,  0.9814074 ,  0.5223155 ,  0.59

In [23]:
data['keypoints'][0].shape

(132,)

In [9]:
data['bone_vectors']

array([[-0.22098406,  0.4485154 ,  0.3731835 , ...,  0.49884802,
         0.01606774,  0.49974176],
       [-0.2227173 ,  0.44765723,  0.3728047 , ...,  0.497993  ,
         0.01648623,  0.49972814],
       [-0.2716056 ,  0.41979805,  0.31863856, ...,  0.49300647,
         0.00905285,  0.49991804],
       ...,
       [-0.09464655, -0.4909603 , -0.01523619, ...,  0.4428401 ,
         0.29833308, -0.4012448 ],
       [-0.09656103, -0.49058738, -0.0148069 , ...,  0.4428565 ,
         0.30885425, -0.39320356],
       [-0.09524848, -0.4908439 , -0.0147612 , ...,  0.4428701 ,
         0.31336743, -0.38961628]], dtype=float32)

In [10]:
data['bone_vectors'].shape

(2093, 70)

In [12]:
type(data['bone_vectors'])

numpy.ndarray

In [18]:
data['bone_vectors'][0].shape

(70,)

In [21]:
data['bone_vectors'][0][]

0.3731835

In [ ]:
#pelda az elso frame ossze vektorara

In [8]:
data['bone_vectors'].shape

(2093, 70)

In [19]:
vector_pairs_1 = (data['bone_vectors'][0]).copy()
vector_pairs_2 = (data['bone_vectors'][0]).copy()

In [20]:
vectors_1 = vector_pairs_2.reshape(35, 2)
vectors_2 = vector_pairs_2.reshape(35, 2)

In [17]:
def cosine_similarity(vec1, vec2):
    # Ensure the vectors are numpy arrays
    vec1 = np.array(vec1)
    vec2 = np.array(vec2)

    # Compute the dot product
    dot_product = np.dot(vec1, vec2)

    # Compute the magnitudes (norms) of the vectors
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)

    # Compute the cosine similarity
    similarity = dot_product / (norm_vec1 * norm_vec2)

    return similarity

In [21]:
# Loop over the pairs of vectors from vectors1 and vectors2
for i in range(len(vectors_1)):
    sim = cosine_similarity(vectors_1[i], vectors_2[i])
    print(f"Cosine similarity between vector {i+1} of array 1 and vector {i+1} of array 2: {sim:.4f}")

Cosine similarity between vector 1 of array 1 and vector 1 of array 2: 1.0000
Cosine similarity between vector 2 of array 1 and vector 2 of array 2: 1.0000
Cosine similarity between vector 3 of array 1 and vector 3 of array 2: 1.0000
Cosine similarity between vector 4 of array 1 and vector 4 of array 2: 1.0000
Cosine similarity between vector 5 of array 1 and vector 5 of array 2: 1.0000
Cosine similarity between vector 6 of array 1 and vector 6 of array 2: 1.0000
Cosine similarity between vector 7 of array 1 and vector 7 of array 2: 1.0000
Cosine similarity between vector 8 of array 1 and vector 8 of array 2: 1.0000
Cosine similarity between vector 9 of array 1 and vector 9 of array 2: 1.0000
Cosine similarity between vector 10 of array 1 and vector 10 of array 2: 1.0000
Cosine similarity between vector 11 of array 1 and vector 11 of array 2: 1.0000
Cosine similarity between vector 12 of array 1 and vector 12 of array 2: 1.0000
Cosine similarity between vector 13 of array 1 and vector 