<a href="https://colab.research.google.com/github/dusarp/dance-bits-experiments/blob/main/similarity_score_test_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#imports
from moviepy.editor import VideoFileClip
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#mount Google Drive
from google.colab import drive


Mounted at /content/gdrive


In [19]:
def extract_beats(audio_file):
    # Load the audio file
    y, sr = librosa.load(audio_file)

    # Use librosa's beat tracking function
    tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)

    # Convert beat frames to time (seconds)
    beat_times = librosa.frames_to_time(beat_frames, sr=sr)

    return beat_times

In [8]:
drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
import os
dancebits_folder = '/content/drive/My Drive/dancebits'

In [10]:
print(os.listdir(dancebits_folder))

['gMH_sFM_c01_d23_mMH3_ch11.mp4', 'PXL_20240924_061040585.TS.p', 'gMH_sFM_c01_d23_mMH3_ch11.p', 'PXL_20240924_061040585.TS.mp4']


In [11]:
video_cristina = VideoFileClip("/content/drive/MyDrive/dancebits/PXL_20240924_061040585.TS.mp4")

In [12]:
video_teaching = VideoFileClip("/content/drive/MyDrive/dancebits/gMH_sFM_c01_d23_mMH3_ch11.mp4")

Cristina video:

In [16]:
#generate the wav from the video file
audio_path = "/content/drive/MyDrive/dancebits/PXL_20240924_061040585.TS.wav"
video_cristina.audio.write_audiofile(audio_path)

MoviePy - Writing audio in /content/drive/MyDrive/dancebits/PXL_20240924_061040585.TS.wav


MoviePy - Done.


In [13]:
#infos about the movie filem:
# Duration in seconds
video = video_cristina
duration = video.duration
print(f"Duration: {duration} seconds")

# Frames per second
fps = video.fps
print(f"FPS: {fps}")

# Resolution (width x height)
resolution = video.size
print(f"Resolution: {resolution[0]}x{resolution[1]}")

# Audio (Check if audio is present)
if video.audio:
    audio_fps = video.audio.fps
    audio_duration = video.audio.duration
    print(f"Audio FPS: {audio_fps}")
    print(f"Audio Duration: {audio_duration} seconds")
else:
    print("No audio track available")

Duration: 33.61 seconds
FPS: 29.83
Resolution: 1920x1080
Audio FPS: 44100
Audio Duration: 33.61 seconds


Teaching video:

In [17]:
#generate the wav from the video file
audio_path = "/content/drive/MyDrive/dancebits/gMH_sFM_c01_d23_mMH3_ch11.wav"
video_teaching.audio.write_audiofile(audio_path)

MoviePy - Writing audio in /content/drive/MyDrive/dancebits/gMH_sFM_c01_d23_mMH3_ch11.wav


MoviePy - Done.


In [14]:
#infos about the movie filem:
# Duration in seconds
video = video_teaching
duration = video.duration
print(f"Duration: {duration} seconds")

# Frames per second
fps = video.fps
print(f"FPS: {fps}")

# Resolution (width x height)
resolution = video.size
print(f"Resolution: {resolution[0]}x{resolution[1]}")

# Audio (Check if audio is present)
if video.audio:
    audio_fps = video.audio.fps
    audio_duration = video.audio.duration
    print(f"Audio FPS: {audio_fps}")
    print(f"Audio Duration: {audio_duration} seconds")
else:
    print("No audio track available")

Duration: 32.05 seconds
FPS: 59.94
Resolution: 1920x1080
Audio FPS: 44100
Audio Duration: 32.05 seconds


In [21]:
extract_beats("/content/drive/MyDrive/dancebits/PXL_20240924_061040585.TS.wav")

array([ 0.06965986,  0.65015873,  1.16099773,  1.69505669,  2.27555556,
        2.80961451,  3.34367347,  3.87773243,  4.41179138,  4.89941043,
        5.41024943,  5.87464853,  6.33904762,  6.87310658,  7.38394558,
        7.91800454,  8.45206349,  8.93968254,  9.45052154,  9.96136054,
       10.47219955, 10.95981859, 11.51709751, 12.07437642, 12.60843537,
       13.14249433, 13.67655329, 14.2338322 , 14.79111111, 15.32517007,
       15.88244898, 16.41650794, 16.95056689, 17.48462585, 17.99546485,
       18.52952381, 19.08680272, 19.64408163, 20.2245805 , 20.80507937,
       21.33913832, 21.89641723, 22.43047619, 22.9877551 , 23.52181406,
       24.07909297, 24.61315193, 25.17043084, 25.7044898 , 26.23854875,
       26.74938776, 27.32988662, 27.86394558, 28.39800454, 28.88562358,
       29.37324263, 29.86086168, 30.32526077, 30.83609977, 31.37015873,
       31.90421769, 32.50793651, 33.06521542, 33.59927438])

In [23]:
teaching_beats = extract_beats("/content/drive/MyDrive/dancebits/gMH_sFM_c01_d23_mMH3_ch11.wav")

In [54]:
print(teaching_beats)

[ 0.60371882  1.13777778  1.69505669  2.22911565  2.7631746   3.32045351
  3.87773243  4.41179138  4.96907029  5.50312925  6.06040816  6.59446712
  7.12852608  7.68580499  8.2430839   8.77714286  9.33442177  9.86848073
 10.40253968 10.95981859 11.49387755 12.05115646 12.60843537 13.14249433
 13.67655329 14.2338322  14.76789116 15.32517007 15.85922902 16.41650794
 16.97378685 17.5078458  18.04190476 18.59918367 19.13324263 19.69052154
 20.2245805  20.78185941 21.33913832 21.87319728 22.40725624 22.96453515
 23.4985941  24.05587302 24.58993197 25.14721088 25.7044898  26.23854875
 26.74938776 27.26022676 27.79428571 28.28190476 28.76952381 29.32680272
 29.9537415  30.44136054 30.9754195 ]


In [33]:
type(teaching_beats)

numpy.ndarray

In [26]:
import math

In [35]:
teaching_beats_frames = np.ceil(teaching_beats * 30)
print(teaching_beats_frames)

[  37.   69.  102.  134.  166.  200.  233.  265.  299.  331.  364.  396.
  428.  462.  495.  527.  561.  593.  625.  658.  690.  724.  757.  789.
  821.  855.  887.  920.  952.  985. 1019. 1051. 1083. 1116. 1148. 1182.
 1214. 1247. 1281. 1313. 1345. 1378. 1410. 1444. 1476. 1509. 1543. 1575.
 1605. 1636. 1668. 1697. 1727. 1760. 1798. 1827. 1859.]


In [36]:
import pickle

In [37]:
# Open the pickle file in binary read mode
with open('/content/drive/MyDrive/dancebits/PXL_20240924_061040585.TS.p', 'rb') as file:
    # Load the contents of the file
    cristina_data = pickle.load(file)

In [38]:
with open('/content/drive/MyDrive/dancebits/gMH_sFM_c01_d23_mMH3_ch11.p', 'rb') as file:
    # Load the contents of the file
    teaching_data = pickle.load(file)

In [39]:
cristina_data['bone_vectors'].shape

(1004, 70)

In [40]:
teaching_data['bone_vectors'].shape

(1921, 70)

In [43]:
vector_pairs_cristina = (cristina_data['bone_vectors']).copy()
vector_pairs_teaching = (teaching_data['bone_vectors']).copy()

In [44]:
vector_pairs_cristina.shape

(1004, 70)

In [45]:
vector_pairs_teaching.shape

(1921, 70)

In [48]:
vectors_cristina = vector_pairs_cristina.reshape(1004, 35, 2)
vectors_teaching = vector_pairs_teaching.reshape(1921, 35, 2)

In [49]:
vectors_cristina[0]

array([[-0.19086258,  0.46213794],
       [-0.12232871, -0.48480478],
       [ 0.24451005, -0.43613625],
       [ 0.48470125, -0.12273841],
       [-0.06738564, -0.49543837],
       [-0.3503713 ,  0.35670707],
       [ 0.48549208,  0.11957186],
       [ 0.44153562,  0.23461947],
       [ 0.04673471,  0.49781108],
       [ 0.46773162, -0.17671198],
       [ 0.3313567 ,  0.37443656],
       [-0.32236335,  0.3822066 ],
       [ 0.28420913, -0.41136986],
       [-0.41895625,  0.2729023 ],
       [-0.4403542 ,  0.23682943],
       [-0.24385986,  0.43650013],
       [ 0.47413182,  0.15874194],
       [-0.48015216,  0.13947724],
       [-0.11448724, -0.4867162 ],
       [-0.4262738 ,  0.2613248 ],
       [ 0.32629395, -0.3788565 ],
       [-0.44150692, -0.23467349],
       [ 0.16621327,  0.47156456],
       [-0.13878417,  0.48035294],
       [ 0.10818632,  0.48815542],
       [-0.01122126,  0.49987406],
       [-0.17220393, -0.46941006],
       [ 0.3817983 ,  0.32284683],
       [ 0.3421492 ,

In [50]:
vectors_teaching[0]

array([[-0.37474048,  0.33101296],
       [ 0.4676813 , -0.17684513],
       [ 0.04631957, -0.49784988],
       [ 0.45445108,  0.20850469],
       [ 0.47071406,  0.16860689],
       [ 0.01922071,  0.49963042],
       [ 0.07380919,  0.49452218],
       [-0.03096388,  0.4990403 ],
       [ 0.11889993,  0.4856571 ],
       [-0.49210027,  0.08852869],
       [-0.02091865,  0.4995622 ],
       [-0.05798398,  0.49662647],
       [ 0.37487197, -0.330864  ],
       [-0.44808415, -0.22185718],
       [-0.4647654 , -0.18437222],
       [ 0.3472683 ,  0.3597287 ],
       [ 0.04124437,  0.498296  ],
       [-0.49973392, -0.01630931],
       [ 0.138226  , -0.48051387],
       [-0.49785203, -0.04629643],
       [ 0.4967126 ,  0.05724159],
       [-0.10542907, -0.48875833],
       [ 0.11796306,  0.4858855 ],
       [-0.09191218,  0.49147955],
       [-0.02600794,  0.49932313],
       [-0.16070683,  0.47346944],
       [ 0.39085197,  0.31182486],
       [ 0.02553705,  0.49934742],
       [-0.05386642,

In [51]:
vectors_teaching_downsample = vectors_teaching[::2]

In [52]:
vectors_teaching_downsample.shape

(961, 35, 2)

first try:

In [75]:
cristina = vectors_cristina[771]

In [74]:
cristina.shape

(35, 2)

In [73]:
teaching = vectors_teaching_downsample[771]

In [72]:
teaching.shape

(35, 2)

In [61]:
def cosine_similarity(vec1, vec2):
    # Ensure the vectors are numpy arrays
    vec1 = np.array(vec1)
    vec2 = np.array(vec2)

    # Compute the dot product
    dot_product = np.dot(vec1, vec2)

    # Compute the magnitudes (norms) of the vectors
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)

    # Compute the cosine similarity
    similarity = dot_product / (norm_vec1 * norm_vec2)

    return similarity

In [71]:
def average_cosine_similarity(list1, list2):
    # Ensure both lists have the same length
    if len(list1) != len(list2):
        raise ValueError("The two lists must have the same number of vectors.")

    # Initialize a variable to store the sum of similarities
    total_similarity = 0

    # Loop over the vectors in both lists
    for vec1, vec2 in zip(list1, list2):
        total_similarity += cosine_similarity(vec1, vec2)

    # Calculate the average similarity
    average_similarity = total_similarity / len(list1)

    return average_similarity

In [76]:
average_cosine_similarity(teaching, cristina)

0.5266115742070334

In [78]:
index_array = np.random.randint(0, 961, size=200)

In [79]:
cristina_random_array = vectors_cristina[index_array]

In [80]:
cristina_random_array.shape

(200, 35, 2)

In [81]:
teaching_random_array = vectors_teaching[index_array]

In [82]:
teaching_random_array.shape

(200, 35, 2)

In [85]:
# Function to apply the cosine similarity computation across all frames of the video
def compute_similarity_for_all_frames(bone_vectors_uploaded, bone_vectors_teaching):
    # Ensure both videos have the same number of frames
    if len(bone_vectors_uploaded) != len(bone_vectors_teaching):
        raise ValueError("The two videos must have the same number of frames.")

    frame_similarities = []

    # Loop through each frame and compute the average similarity for the frame
    for frame_idx in range(len(bone_vectors_uploaded)):
        uploaded_frame = bone_vectors_uploaded[frame_idx]
        teaching_frame = bone_vectors_teaching[frame_idx]

        # Compute average cosine similarity for the frame
        frame_similarity = average_cosine_similarity(uploaded_frame, teaching_frame)
        frame_similarities.append(frame_similarity)

    # Compute the overall average similarity across all frames
    overall_similarity = np.mean(frame_similarities)

    return overall_similarity

In [86]:
compute_similarity_for_all_frames(teaching_random_array, cristina_random_array)

0.5253785632830903

Alignment, delta /2 leveve Crist elejerol es vegerol

In [87]:
vectors_cristina_delta = vectors_cristina[21:-21, :, :]

In [88]:
vectors_cristina_delta.shape

(962, 35, 2)

In [89]:
vectors_teaching_downsample.shape

(961, 35, 2)

In [90]:
cristina_delta_random_array = vectors_cristina_delta[index_array]

In [91]:
cristina_delta_random_array.shape

(200, 35, 2)

In [92]:
teaching_random_array.shape

(200, 35, 2)

In [93]:
compute_similarity_for_all_frames(teaching_random_array, cristina_delta_random_array)

0.5342205923203229

All

In [94]:
vectors_teaching_downsample.shape

(961, 35, 2)

In [97]:
vectors_cristina_delta_all = vectors_cristina[21:-22, :, :]

In [98]:
vectors_cristina_delta_all.shape

(961, 35, 2)

In [99]:
compute_similarity_for_all_frames(vectors_teaching_downsample, vectors_cristina_delta_all)

0.6228478433015514

In [101]:
compute_similarity_for_all_frames(vectors_cristina_delta_all, vectors_cristina_delta_all)

1.000000027655421